# 运行模式 dev or prod
runmode: dev

# 小程序配置
wechat:
  appid:
  secret:
# ID混淆加盐
hashidssalt:
database:
  dialect:
  database:
  user:
  password:
  charset: utf8mb4
  host: localhost
  port: 3306
  maxidleconns: 5
  maxopenconns: 10
redisconfig:
  host: localhost
  port: 6379
  password:
  maxidle: 3
  maxactive: 5
wechatpay:
  appid:
  mchid:
  paysecret:
